import type { CompanyProductSettings } from './settings.types';

type CatalogDefinition = readonly [
  category: string,
  name: string,
  about: string,
  targetAudience: string,
  solutionObjective: string,
];

const catalog: CatalogDefinition[] = [
  ['Gestao e Backoffice', 'TOTVS Backoffice - Linha Protheus', 'ERP de gestao financeira, fiscal, estoque, compras, vendas e operacoes.', 'Empresas pequenas, medias e grandes.', 'Integrar a gestao da empresa.'],
  ['Gestao e Backoffice', 'TOTVS Backoffice - Linha RM', 'ERP administrativo, financeiro, fiscal, RH, educacao, saude e construcao.', 'Empresas com operacao administrativa forte.', 'Controlar processos internos e reduzir retrabalho.'],
  ['Gestao e Backoffice', 'TOTVS Backoffice - Linha Datasul', 'ERP para backoffice e operacoes industriais ou complexas.', 'Industrias, agro, logistica e saude.', 'Integrar operacao, producao e gestao.'],
  ['Gestao e Backoffice', 'TOTVS Backoffice - Linha Logix', 'ERP para gestao administrativa e operacional.', 'Industria, logistica, distribuicao e servicos.', 'Dar controle para operacoes medias e grandes.'],
  ['Gestao e Backoffice', 'TOTVS Automacao de Testes - Linha RM', 'Testes automatizados no ambiente RM.', 'TI e sustentacao RM.', 'Validar mudancas com menos erro.'],
  ['Gestao e Backoffice', 'TOTVS API Services', 'Servicos de integracao por API.', 'Empresas que integram sistemas.', 'Conectar TOTVS com outros sistemas.'],
  ['Gestao e Backoffice', 'TOTVS Conector - Linha Gesplan', 'Integracao com solucoes Gesplan.', 'Financeiro e controladoria.', 'Conectar planejamento e backoffice.'],
  ['Gestao e Backoffice', 'TOTVS Central do Cliente', 'Portal de relacionamento com cliente.', 'Empresas que atendem clientes externos.', 'Centralizar atendimento e solicitacoes.'],
  ['Gestao e Backoffice', 'TOTVS Gestao Financeira - Linha Gesplan', 'Gestao financeira e planejamento.', 'Financeiro, controladoria e diretoria.', 'Melhorar controle financeiro.'],
  ['Gestao e Backoffice', 'TOTVS Gestao de Receitas', 'Gestao de receitas e faturamento.', 'Empresas com cobranca recorrente ou complexa.', 'Controlar receita e previsibilidade.'],
  ['Gestao e Backoffice', 'TOTVS Portal de Vendas', 'Portal para vendas e pedidos.', 'Times comerciais e clientes B2B.', 'Facilitar pedidos e relacionamento comercial.'],
  ['Gestao e Backoffice', 'TOTVS Transmite', 'Gestao e transmissao de documentos fiscais.', 'Fiscal e contabilidade.', 'Garantir controle fiscal.'],
  ['Gestao e Backoffice', 'Classificador Fiscal by Busca.Legal', 'Classificacao fiscal de produtos.', 'Fiscal, compras e cadastro.', 'Reduzir erro tributario.'],
  ['Gestao e Backoffice', 'Classificacao Tributaria by Systax', 'Regras tributarias e classificacao.', 'Fiscal e compliance.', 'Aumentar seguranca tributaria.'],
  ['Gestao e Backoffice', 'Auditor Fiscal by Neogrid', 'Auditoria de documentos fiscais.', 'Fiscal e compliance.', 'Identificar inconsistencias fiscais.'],
  ['Gestao e Backoffice', 'Inteligencia Fiscal by IOB', 'Consulta e inteligencia fiscal.', 'Fiscal, contabil e juridico tributario.', 'Apoiar decisoes tributarias.'],
  ['Gestao e Backoffice', 'Licitacoes by Portal de Contas Publicas', 'Gestao de licitacoes.', 'Empresas que vendem para governo.', 'Encontrar e gerenciar oportunidades publicas.'],
  ['Gestao e Backoffice', 'Planejamento Orcamentario by Prophix', 'Planejamento e orcamento corporativo.', 'Controladoria e diretoria.', 'Planejar orcamento com dados.'],
  ['Gestao e Backoffice', 'Servico de Integracao by Prophix', 'Integracao com planejamento orcamentario.', 'Controladoria e TI.', 'Conectar dados financeiros.'],
  ['Gestao e Backoffice', 'App Meu Protheus', 'Acesso mobile a operacoes do Protheus.', 'Usuarios do ERP Protheus.', 'Consultar e executar rotinas pelo celular.'],
  ['Gestao e Backoffice', 'App Minhas Vendas', 'Acompanhamento mobile de vendas.', 'Equipes comerciais.', 'Acelerar gestao de pedidos e vendas.'],
  ['Gestao e Backoffice', 'App Meu Patrimonio', 'Consulta e operacao de patrimonio.', 'Financeiro e administracao.', 'Controlar ativos de forma movel.'],
  ['Gestao e Backoffice', 'App Meus Orcamentos', 'Gestao mobile de orcamentos.', 'Times comerciais e gestores.', 'Acompanhar propostas com agilidade.'],
  ['Gestao e Backoffice', 'App Minha Contagem de Estoque', 'Contagem de estoque em dispositivo movel.', 'Estoquistas e operacoes.', 'Agilizar inventarios.'],
  ['Gestao e Backoffice', 'App Meu Coletor de Dados', 'Coleta operacional de dados.', 'Operacoes e logistica.', 'Registrar informacoes em campo.'],
  ['Gestao e Backoffice', 'App Minhas Pendencias de Aprovacao', 'Aprovacao de pendencias pelo celular.', 'Gestores e aprovadores.', 'Reduzir tempo de aprovacao.'],

  ['RH', 'TOTVS RH Folha de Pagamento - Linha Protheus', 'Processar folha, encargos e obrigacoes.', 'Departamento pessoal.', 'Pagar corretamente e cumprir legislacao.'],
  ['RH', 'TOTVS RH Folha de Pagamento - Linha Datasul', 'Folha integrada ao Datasul.', 'Empresas que usam Datasul.', 'Automatizar folha.'],
  ['RH', 'TOTVS RH Folha de Pagamento - Linha RM', 'Folha integrada ao RM.', 'Empresas que usam RM.', 'Controlar folha e eSocial.'],
  ['RH', 'TOTVS RH Ponto Eletronico - Linha Ahgora', 'Controle de ponto e jornada.', 'RH e departamento pessoal.', 'Controlar horas e banco de horas.'],
  ['RH', 'TOTVS RH Ponto Eletronico - Linha Protheus', 'Ponto integrado ao Protheus.', 'Empresas com Protheus.', 'Integrar ponto e folha.'],
  ['RH', 'TOTVS RH Ponto Eletronico - Linha Datasul', 'Ponto integrado ao Datasul.', 'Empresas com Datasul.', 'Controlar jornada.'],
  ['RH', 'TOTVS RH Ponto Eletronico - Linha RM', 'Ponto integrado ao RM.', 'Empresas com RM.', 'Automatizar jornada e folha.'],
  ['RH', 'TOTVS RH Admissao Digital', 'Admissao online.', 'RH e departamento pessoal.', 'Reduzir papel e acelerar contratacao.'],
  ['RH', 'TOTVS RH Atracao de Talentos', 'Recrutamento e selecao.', 'RH e recrutadores.', 'Atrair e contratar candidatos.'],
  ['RH', 'TOTVS RH Atracao de Talentos - Linha Feedz', 'Recrutamento na linha Feedz.', 'Pequenas e medias empresas.', 'Simplificar selecao.'],
  ['RH', 'TOTVS RH Avaliacao de Desempenho', 'Avaliar performance.', 'RH e gestores.', 'Medir desempenho e evolucao.'],
  ['RH', 'TOTVS RH Avaliacao de Desempenho - Linha Feedz', 'Avaliacao na linha Feedz.', 'Empresas que usam Feedz.', 'Tornar avaliacao mais simples.'],
  ['RH', 'TOTVS RH Clima e Engajamento', 'Pesquisa de clima.', 'RH estrategico.', 'Medir satisfacao e engajamento.'],
  ['RH', 'TOTVS RH Clima e Engajamento - Linha Feedz', 'Clima na linha Feedz.', 'Empresas com Feedz.', 'Monitorar cultura e engajamento.'],
  ['RH', 'TOTVS RH Metas e Objetivos (OKR)', 'Gestao de metas e OKRs.', 'Times e liderancas.', 'Alinhar estrategia e execucao.'],
  ['RH', 'TOTVS RH Metas e Objetivos - Linha Feedz', 'OKRs na linha Feedz.', 'Empresas com Feedz.', 'Acompanhar metas.'],
  ['RH', 'TOTVS RH People Analytics', 'Indicadores de pessoas.', 'RH e diretoria.', 'Decidir com dados de RH.'],
  ['RH', 'TOTVS RH Orcamento', 'Planejamento orcamentario de RH.', 'RH e financeiro.', 'Controlar custos de pessoal.'],
  ['RH', 'TOTVS RH Medicina e Seguranca do Trabalho', 'SST, exames e seguranca ocupacional.', 'RH, DP e seguranca do trabalho.', 'Cumprir normas trabalhistas.'],
  ['RH', 'Saude e Seguranca do Trabalho by NG', 'SST complementar.', 'Empresas com obrigacoes de seguranca.', 'Controlar riscos ocupacionais.'],
  ['RH', 'Acesso e Seguranca by Suricato', 'Controle de acesso fisico e digital.', 'Empresas com controle de entrada.', 'Aumentar seguranca.'],
  ['RH', 'Beneficios Flexiveis by Swile', 'Gestao de beneficios.', 'RH e colaboradores.', 'Flexibilizar beneficios.'],
  ['RH', 'Digital Workplace by Digte', 'Ambiente digital de trabalho.', 'Empresas com comunicacao interna.', 'Melhorar experiencia do colaborador.'],
  ['RH', 'LMS + LXP by Afferolab', 'Treinamento e aprendizagem.', 'RH e educacao corporativa.', 'Capacitar colaboradores.'],
  ['RH', 'TOTVS RH Mapeamento Comportamental', 'Perfil comportamental.', 'RH e liderancas.', 'Entender perfis e times.'],
  ['RH', 'TOTVS RH Mapeamento Comportamental - Linha Feedz', 'Mapeamento na linha Feedz.', 'Empresas com Feedz.', 'Apoiar decisoes de pessoas.'],
  ['RH', 'App Meu RH', 'Aplicativo do colaborador.', 'Funcionarios e gestores.', 'Consultar holerite, ferias e solicitacoes.'],
  ['RH', 'TOTVS RH Clock In', 'Registro de ponto digital.', 'Colaboradores.', 'Marcar ponto de forma simples.'],
  ['RH', 'App Meu Clock In', 'Aplicativo de ponto.', 'Funcionarios externos e hibridos.', 'Registrar jornada pelo celular.'],

  ['CRM, Vendas e Marketing', 'TOTVS CRM Gestao de Clientes', 'Gestao de clientes, oportunidades e relacionamento.', 'Times comerciais.', 'Organizar vendas e clientes.'],
  ['CRM, Vendas e Marketing', 'TOTVS CRM SFA / Automacao da Forca de Vendas', 'Gestao de vendedores externos, visitas e pedidos.', 'Equipes comerciais de campo.', 'Aumentar produtividade de vendas.'],
  ['CRM, Vendas e Marketing', 'Meu CRM', 'CRM simplificado.', 'Pequenas equipes comerciais.', 'Controlar funil e contatos.'],
  ['CRM, Vendas e Marketing', 'RD Station Marketing', 'Automacao de marketing, landing pages, email e nutricao de leads.', 'Marketing e growth.', 'Atrair e qualificar leads.'],
  ['CRM, Vendas e Marketing', 'RD Station CRM', 'Funil de vendas, automacoes e gestao comercial.', 'Vendedores e gestores.', 'Aumentar previsibilidade de vendas.'],
  ['CRM, Vendas e Marketing', 'RD Station Conversas', 'Atendimento multicanal com WhatsApp, chatbots e IA.', 'Atendimento, vendas e suporte.', 'Centralizar conversas e converter mais.'],
  ['CRM, Vendas e Marketing', 'RD Station Marketing para ecommerce', 'Marketing para lojas virtuais.', 'E-commerces.', 'Criar estrategia multicanal para vender online.'],
  ['CRM, Vendas e Marketing', 'RD Station Mentor IA', 'IA para conteudo, qualificacao e conversao.', 'Marketing e vendas.', 'Automatizar criacao e qualificacao.'],

  ['Fluig, Processos e Identidade', 'TOTVS Fluig', 'Workflow, documentos, processos e colaboracao.', 'Empresas com muitos fluxos internos.', 'Automatizar processos.'],
  ['Fluig, Processos e Identidade', 'TOTVS Identity', 'Login unico, SSO e controle de acesso.', 'TI e seguranca.', 'Centralizar autenticacao.'],
  ['Fluig, Processos e Identidade', 'Gestao de Cadastros by EZ4', 'Cadastro e governanca de dados.', 'Operacoes e cadastro.', 'Melhorar qualidade cadastral.'],
  ['Fluig, Processos e Identidade', 'Gestao de Processos e Atividades by Xplanning', 'Controle de processos e atividades.', 'Operacoes.', 'Organizar execucao de tarefas.'],
  ['Fluig, Processos e Identidade', 'OCR by Estrela Antares', 'Leitura automatica de documentos.', 'Fiscal, financeiro e backoffice.', 'Reduzir digitacao manual.'],
  ['Fluig, Processos e Identidade', 'Process Mining by Upflux', 'Analise de processos reais.', 'Operacoes e melhoria continua.', 'Descobrir gargalos.'],
  ['Fluig, Processos e Identidade', 'Public Form by Digte', 'Formularios publicos digitais.', 'Empresas que coletam dados externos.', 'Digitalizar entrada de informacoes.'],
  ['Fluig, Processos e Identidade', 'App My Safe ID', 'Aplicativo ligado a identidade e acesso.', 'Usuarios corporativos.', 'Aumentar seguranca.'],
  ['Fluig, Processos e Identidade', 'App My Approval', 'Aprovacoes pelo aplicativo.', 'Gestores.', 'Agilizar aprovacoes.'],
  ['Fluig, Processos e Identidade', 'App My Fluig', 'Acesso mobile ao Fluig.', 'Usuarios Fluig.', 'Usar processos pelo celular.'],

  ['Analytics, BI e Dados', 'TOTVS Analytics', 'Dashboards e indicadores.', 'Gestores e diretoria.', 'Tomar decisao com dados.'],
  ['Analytics, BI e Dados', 'Insights by Targit', 'BI e analises avancadas.', 'Controladoria, BI e gestao.', 'Analisar performance.'],
  ['Analytics, BI e Dados', 'People Analytics', 'Indicadores de RH.', 'RH e diretoria.', 'Analisar dados de pessoas.'],
  ['Analytics, BI e Dados', 'App Meu Analytics', 'Analytics no celular.', 'Gestores.', 'Consultar indicadores rapidamente.'],
  ['Analytics, BI e Dados', 'BI by TARGIT', 'Business Intelligence.', 'Empresas com analise de dados.', 'Monitorar indicadores.'],
  ['Analytics, BI e Dados', 'Data Insights by H2J', 'Insights de dados.', 'Varejo e gestao.', 'Apoiar decisoes comerciais.'],
  ['Analytics, BI e Dados', 'Analytics by Falcon', 'Analytics segmentado.', 'Varejo e operacoes.', 'Melhorar analise operacional.'],
  ['Analytics, BI e Dados', 'Pricing Insights', 'Inteligencia de precos.', 'Varejo e supermercados.', 'Melhorar precificacao.'],

  ['Digital Commerce', 'Chat Commerce by Chatbot Maker', 'Comercio via chat.', 'Vendas digitais.', 'Vender por canais conversacionais.'],
  ['Digital Commerce', 'TOTVS Integrador de Marketplaces', 'Integra loja ou ERP com marketplaces.', 'E-commerce e varejo.', 'Centralizar vendas online.'],
  ['Digital Commerce', 'Plataforma de Marketplace by Omnik', 'Criar e operar marketplace.', 'Empresas com venda online.', 'Escalar canais digitais.'],
  ['Digital Commerce', 'Venda Digital by Ninegrid', 'Venda digital.', 'Varejo e distribuicao.', 'Digitalizar vendas.'],
  ['Digital Commerce', 'Conector Marketplaces by Hyperlocal', 'Integracao com marketplaces.', 'Food service e varejo.', 'Conectar pedidos externos.'],
  ['Digital Commerce', 'Comercio B2B by teceo', 'Venda B2B digital.', 'Moda e industria.', 'Facilitar vendas entre empresas.'],

  ['Techfin e Servicos Financeiros', 'TOTVS Antecipa', 'Antecipacao de recebiveis.', 'Empresas que vendem a prazo.', 'Melhorar fluxo de caixa.'],
  ['Techfin e Servicos Financeiros', 'TOTVS + Giro', 'Capital de giro.', 'Empresas que precisam financiar operacao.', 'Dar folego financeiro.'],
  ['Techfin e Servicos Financeiros', 'TOTVS + Prazo', 'Prazo maior para pagamento.', 'Empresas compradoras.', 'Organizar caixa.'],
  ['Techfin e Servicos Financeiros', 'TOTVS + Vendas', 'Credito para clientes comprarem.', 'Empresas vendedoras.', 'Aumentar vendas.'],
  ['Techfin e Servicos Financeiros', 'TOTVS Recebe + Conciliado', 'Conciliacao de recebimentos.', 'Financeiro.', 'Automatizar baixa e conciliacao.'],
  ['Techfin e Servicos Financeiros', 'TOTVS Recebe + Programado', 'Recebimento programado.', 'Financeiro.', 'Prever recebimentos.'],
  ['Techfin e Servicos Financeiros', 'TOTVS Recebe + Multibanco', 'Gestao de multiplos bancos.', 'Financeiro.', 'Centralizar recebiveis.'],
  ['Techfin e Servicos Financeiros', 'TOTVS Recebe + Boleto Hibrido', 'Boleto com meios modernos, como Pix.', 'Cobranca e financeiro.', 'Facilitar pagamento.'],
  ['Techfin e Servicos Financeiros', 'TOTVS Consignado Marketplace', 'Solucao de credito consignado.', 'Empresas e parceiros.', 'Oferecer credito integrado.'],

  ['Agro', 'TOTVS Beneficiamento', 'Gestao de beneficiamento agricola.', 'Agroindustrias.', 'Controlar processamento.'],
  ['Agro', 'TOTVS Beneficiamento - Linha Protheus', 'Beneficiamento integrado ao Protheus.', 'Empresas agro com Protheus.', 'Integrar agro e ERP.'],
  ['Agro', 'TOTVS Bioenergia', 'Gestao de usinas e bioenergia.', 'Usinas e setor sucroenergetico.', 'Controlar producao e operacao.'],
  ['Agro', 'TOTVS Multicultivo', 'Gestao de multiplas culturas.', 'Fazendas e grupos agricolas.', 'Controlar producao agricola.'],
  ['Agro', 'TOTVS Agro Distribuidor - Linha Protheus', 'Gestao para distribuidor agro.', 'Distribuidores agricolas.', 'Controlar vendas, estoque e operacao.'],
  ['Agro', 'TOTVS Comercializacao - Linha Protheus', 'Comercializacao agricola.', 'Agroindustrias e tradings.', 'Controlar contratos e vendas.'],
  ['Agro', 'TOTVS Comercializacao - Linha Datasul', 'Comercializacao no Datasul.', 'Empresas agro com Datasul.', 'Integrar comercializacao ao ERP.'],
  ['Agro', 'TOTVS Comercializacao de Commodities', 'Comercializacao de commodities.', 'Tradings e agro.', 'Controlar compra e venda de commodities.'],
  ['Agro', 'TOTVS Portal Agricola', 'Portal para operacoes agricolas.', 'Produtores, fornecedores e agroindustrias.', 'Integrar informacoes do campo.'],
  ['Agro', 'TOTVS Fitossanitario', 'Controle fitossanitario.', 'Agronegocio.', 'Controlar defensivos e aplicacoes.'],
  ['Agro', 'TOTVS Pesagem', 'Controle de balanca e pesagem.', 'Agro, logistica e industria.', 'Registrar entradas e saidas.'],
  ['Agro', 'TOTVS Coleta e Entrega', 'Gestao de coletas e entregas.', 'Operacoes logisticas agro.', 'Controlar entregas.'],
  ['Agro', 'TOTVS Roteirizacao e Entregas', 'Roteiros e entregas.', 'Distribuicao, agro e logistica.', 'Otimizar rotas.'],
  ['Agro', 'TOTVS WMS SaaS', 'Gestao de armazem.', 'Armazens e centros de distribuicao.', 'Controlar estoque fisico.'],
  ['Agro', 'TOTVS YMS', 'Gestao de patio.', 'Centros logisticos.', 'Controlar entrada e saida de veiculos.'],
  ['Agro', 'App Meu Agro Indicadores', 'Indicadores agricolas no celular.', 'Gestores agro.', 'Acompanhar operacao em campo.'],
  ['Agro', 'App Meu Portal Agricola', 'Acesso mobile ao portal agricola.', 'Produtores e operacoes.', 'Consultar operacoes remotamente.'],
  ['Agro', 'App Meu Controle Fitossanitario', 'Controle mobile de aplicacoes.', 'Equipes agricolas.', 'Registrar controle fitossanitario.'],
  ['Agro', 'App Minha Coleta e Entrega', 'Registro mobile de coleta e entrega.', 'Logistica agro.', 'Dar visibilidade as entregas.'],
  ['Agro', 'App Meu Rastreamento de Entregas', 'Rastreamento no celular.', 'Gestores e clientes.', 'Acompanhar entregas.'],
  ['Agro', 'App Meu WMS SaaS', 'Acesso mobile ao WMS.', 'Operacao de armazem.', 'Controlar armazenagem em campo.'],

  ['Construcao', 'TOTVS Gestao de Imoveis', 'Gestao imobiliaria.', 'Incorporadoras e construtoras.', 'Controlar imoveis, vendas e contratos.'],
  ['Construcao', 'TOTVS Obras e Projetos', 'Gestao de obras.', 'Construtoras.', 'Controlar orcamento, execucao e projeto.'],
  ['Construcao', 'TOTVS Gestao de Shopping Center', 'Gestao de shopping.', 'Administradoras de shopping.', 'Controlar lojas, contratos e operacao.'],
  ['Construcao', 'TOTVS Portal de Imoveis', 'Portal para imoveis.', 'Construtoras e incorporadoras.', 'Facilitar atendimento e consulta.'],
  ['Construcao', 'TOTVS Aprovacoes e Atendimento', 'Fluxos de aprovacao e atendimento.', 'Construcao, educacao e saude.', 'Agilizar solicitacoes.'],
  ['Construcao', 'Base de Dados Construcao by OrceCerto', 'Base de custos e orcamentos.', 'Construcao civil.', 'Apoiar orcamento de obra.'],
  ['Construcao', 'Conversas by Worknow', 'Comunicacao e atendimento.', 'Construcao e educacao.', 'Centralizar conversas.'],
  ['Construcao', 'Indicacoes Imobiliarias by OQDigital', 'Indicacoes para vendas imobiliarias.', 'Imobiliarias e incorporadoras.', 'Gerar oportunidades.'],
  ['Construcao', 'App Minha Obra', 'Acompanhamento de obra no celular.', 'Equipes de obra.', 'Controlar execucao em campo.'],
  ['Construcao', 'App Minhas Inspecoes', 'Inspecoes em campo.', 'Engenharia e qualidade.', 'Registrar vistorias.'],
  ['Construcao', 'App Meu Imovel', 'Aplicativo para cliente e imovel.', 'Clientes e incorporadoras.', 'Acompanhar informacoes do imovel.'],

  ['Distribuicao', 'TOTVS Distribuicao e Varejo - Linha Winthor', 'ERP para atacado e distribuicao.', 'Distribuidores e atacadistas.', 'Controlar vendas, estoque e financeiro.'],
  ['Distribuicao', 'TOTVS WMS - Linha Winthor', 'Gestao de armazem Winthor.', 'Centros de distribuicao e distribuidores.', 'Controlar separacao e estoque.'],
  ['Distribuicao', 'App Meu WinThor', 'Aplicativo para usuarios Winthor.', 'Equipes operacionais.', 'Facilitar acesso mobile.'],
  ['Distribuicao', 'App Meu WinThor RF', 'Coleta via radiofrequencia.', 'Operacao de estoque.', 'Agilizar movimentacao.'],
  ['Distribuicao', 'Automacao de Vendas by N3urons', 'Automacao comercial.', 'Distribuidores.', 'Vender com mais eficiencia.'],
  ['Distribuicao', 'Cobranca Digital by Pague Bem Brasil', 'Cobranca digital.', 'Financeiro e cobranca.', 'Facilitar recebimento.'],
  ['Distribuicao', 'Inteligencia de Estoque by Systock', 'Otimizacao de estoque.', 'Distribuicao e varejo.', 'Evitar ruptura e excesso.'],
  ['Distribuicao', 'Inteligencia de Vendas by N3urons', 'Inteligencia comercial.', 'Vendas e gestao.', 'Melhorar performance comercial.'],
  ['Distribuicao', 'Plataforma B2B by Isthmus', 'Portal B2B.', 'Distribuidores.', 'Vender online para clientes B2B.'],
  ['Distribuicao', 'TOTVS OMS', 'Gestao de pedidos omnichannel.', 'Varejo e distribuicao.', 'Orquestrar pedidos.'],
  ['Distribuicao', 'TOTVS TEF', 'Transferencia eletronica de fundos.', 'Varejo e distribuicao.', 'Integrar pagamentos com cartao.'],

  ['Logistica', 'TOTVS TMS', 'Gestao de transporte.', 'Transportadoras e operadores logisticos.', 'Controlar fretes, entregas e custos.'],
  ['Logistica', 'TOTVS TMS SaaS', 'TMS em nuvem.', 'Logistica com modelo SaaS.', 'Gerir transporte com menor infraestrutura.'],
  ['Logistica', 'TOTVS WMS - Linha Logix', 'Armazem integrado ao Logix.', 'Operadores logisticos.', 'Controlar estoque e armazem.'],
  ['Logistica', 'TOTVS Portal Logistico', 'Portal para logistica.', 'Embarcadores, transportadoras e clientes.', 'Dar visibilidade operacional.'],
  ['Logistica', 'TOTVS Frete Embarcador', 'Gestao de frete para embarcador.', 'Empresas que contratam transporte.', 'Controlar contratacao e custo de frete.'],
  ['Logistica', 'TOTVS Monitoramento Logistico', 'Monitoramento de entregas.', 'Operacoes logisticas.', 'Acompanhar operacao em tempo real.'],
  ['Logistica', 'TOTVS Tracking', 'Rastreamento.', 'Operacoes de entrega.', 'Dar visibilidade ao cliente e a operacao.'],
  ['Logistica', 'TOTVS Recintos Aduaneiros', 'Gestao de recintos alfandegados.', 'Portos e zonas alfandegadas.', 'Controlar operacao aduaneira.'],
  ['Logistica', 'TOTVS Automacao de Terminais', 'Gestao de terminais.', 'Portos e terminais.', 'Automatizar operacao de terminal.'],
  ['Logistica', 'Carbono IA by Deep', 'Calculo e gestao de carbono com IA.', 'Logistica e industria.', 'Medir impacto ambiental.'],
  ['Logistica', 'Gestao ESG by Deep', 'Gestao ESG.', 'Empresas com metas ESG.', 'Controlar indicadores sustentaveis.'],

  ['Manufatura', 'TOTVS Manufatura - Linha Datasul', 'ERP industrial Datasul.', 'Industrias.', 'Controlar producao e operacao.'],
  ['Manufatura', 'TOTVS Manufatura - Linha Protheus', 'ERP industrial Protheus.', 'Industrias com Protheus.', 'Integrar producao ao ERP.'],
  ['Manufatura', 'TOTVS Manufatura - Linha Logix', 'ERP industrial Logix.', 'Industrias maiores ou complexas.', 'Controlar chao de fabrica e gestao.'],
  ['Manufatura', 'TOTVS APS', 'Planejamento avancado da producao.', 'PCP e industria.', 'Otimizar capacidade e programacao.'],
  ['Manufatura', 'MES by PPI-Multitask', 'Execucao de manufatura.', 'Chao de fabrica.', 'Acompanhar producao em tempo real.'],
  ['Manufatura', 'TOTVS Manutencao de Ativos - Linha Datasul', 'Manutencao industrial.', 'Industrias com Datasul.', 'Controlar ativos e manutencao.'],
  ['Manufatura', 'TOTVS Manutencao de Ativos - Linha Protheus', 'Manutencao industrial no Protheus.', 'Industrias com Protheus.', 'Reduzir paradas.'],
  ['Manufatura', 'TOTVS Comercio Exterior', 'Gestao de comercio exterior.', 'Empresas importadoras e exportadoras.', 'Controlar operacoes internacionais.'],
  ['Manufatura', 'TOTVS Importacao e Exportacao', 'Importacao e exportacao.', 'Industrias e comercio exterior.', 'Controlar processos internacionais.'],
  ['Manufatura', 'TOTVS Gestao Ambiental', 'Gestao ambiental.', 'Industrias.', 'Controlar obrigacoes ambientais.'],
  ['Manufatura', 'TOTVS Moda', 'Gestao para moda e confeccao.', 'Industria e varejo de moda.', 'Controlar producao e venda de moda.'],
  ['Manufatura', 'RPA by Automation Anywhere', 'Automacao robotica de processos.', 'Empresas com tarefas repetitivas.', 'Automatizar rotinas.'],
  ['Manufatura', 'S&OP by Neogrid', 'Planejamento de vendas e operacoes.', 'Industria, distribuicao e varejo.', 'Alinhar demanda e producao.'],
  ['Manufatura', 'Homologacao de Fornecedores by Mercado Eletronico', 'Homologar fornecedores.', 'Compras e suprimentos.', 'Reduzir risco em fornecedores.'],
  ['Manufatura', 'Gestao de Contratos by Mercado Eletronico', 'Gestao de contratos.', 'Compras e juridico.', 'Controlar contratos e prazos.'],
  ['Manufatura', 'Avaliacao de Fornecedores by Mercado Eletronico', 'Avaliar fornecedores.', 'Suprimentos.', 'Melhorar performance da cadeia.'],
  ['Manufatura', 'App Minha Producao - Linha Protheus', 'Aplicativo de producao.', 'Chao de fabrica.', 'Registrar producao pelo celular.'],
  ['Manufatura', 'App Minha Producao - Linha Datasul', 'Aplicativo de producao Datasul.', 'Chao de fabrica.', 'Acompanhar producao.'],
  ['Manufatura', 'App Minha Manutencao de Ativos - Linha Protheus', 'Aplicativo de manutencao.', 'Manutencao industrial.', 'Registrar manutencao em campo.'],
  ['Manufatura', 'App Minha Manutencao de Ativos - Linha Datasul', 'Aplicativo de manutencao Datasul.', 'Manutencao industrial.', 'Agilizar ordens de manutencao.'],

  ['Prestadores de Servicos', 'TOTVS Field Service', 'Gestao de servicos em campo.', 'Empresas de assistencia, manutencao e servicos externos.', 'Controlar ordens e equipes externas.'],
  ['Prestadores de Servicos', 'TOTVS Rental', 'Gestao de locacao.', 'Locadoras de equipamentos.', 'Controlar contratos e ativos locados.'],
  ['Prestadores de Servicos', 'TOTVS Terceirizacao', 'Gestao de terceirizacao.', 'Empresas de mao de obra terceirizada.', 'Controlar contratos, postos e equipes.'],
  ['Prestadores de Servicos', 'Gestao Deathcare by Duofy', 'Gestao funeraria e deathcare.', 'Empresas do segmento deathcare.', 'Controlar atendimento e operacao.'],
  ['Prestadores de Servicos', 'Ronda de Trabalho by FindMe', 'Rondas operacionais.', 'Seguranca e facilities.', 'Monitorar rondas.'],
  ['Prestadores de Servicos', 'Supervisor de Posto de Trabalho by FindMe', 'Supervisao de postos.', 'Facilities e terceirizacao.', 'Controlar presenca e atividades.'],
  ['Prestadores de Servicos', 'App Minha Gestao de Postos', 'Gestao mobile de postos.', 'Supervisores.', 'Acompanhar postos em campo.'],
  ['Prestadores de Servicos', 'App Minhas Ordens de Servicos', 'Ordens de servico no celular.', 'Equipes externas.', 'Registrar servicos.'],
  ['Prestadores de Servicos', 'App Meu Posto de Trabalho', 'Aplicativo para posto de trabalho.', 'Colaboradores alocados.', 'Facilitar rotina operacional.'],

  ['Saude', 'TOTVS Hospitais e Clinicas', 'Gestao hospitalar e clinica.', 'Hospitais e clinicas.', 'Controlar atendimento e operacao.'],
  ['Saude', 'TOTVS Planos - Linha Datasul', 'Gestao de operadoras de saude.', 'Planos de saude com Datasul.', 'Controlar beneficiarios, contas e operacao.'],
  ['Saude', 'TOTVS Planos - Linha Protheus', 'Gestao de planos no Protheus.', 'Operadoras de saude.', 'Integrar gestao ao ERP.'],
  ['Saude', 'TOTVS Saude Consultorios', 'Gestao de consultorios.', 'Clinicas e consultorios.', 'Controlar agenda, atendimento e financeiro.'],
  ['Saude', 'TOTVS Saude Gestor TISS', 'Gestao TISS.', 'Operadoras e prestadores.', 'Controlar padrao TISS.'],
  ['Saude', 'TOTVS Portal Autorizador', 'Autorizacoes de saude.', 'Operadoras e prestadores.', 'Controlar autorizacoes.'],
  ['Saude', 'Ciclo de Receita by UpFlux', 'Gestao do ciclo de receita.', 'Hospitais e clinicas.', 'Reduzir perdas e melhorar faturamento.'],
  ['Saude', 'Health Analytics by Horuss AI', 'Analytics em saude.', 'Gestao hospitalar e saude.', 'Analisar dados assistenciais.'],
  ['Saude', 'Insights by Horuss AI', 'Insights com IA.', 'Saude.', 'Apoiar decisao clinica e operacional.'],
  ['Saude', 'Internacao e Desospitalizacao by UpFlux', 'Gestao de internacao e desospitalizacao.', 'Hospitais e operadoras.', 'Melhorar fluxo assistencial.'],
  ['Saude', 'Pos-auditoria em Saude by UpFlux', 'Auditoria pos-atendimento.', 'Saude e faturamento.', 'Reduzir glosas e inconsistencias.'],

  ['Varejo', 'TOTVS DMS', 'Gestao de concessionarias e dealers.', 'Concessionarias e setor automotivo.', 'Controlar vendas, oficina e pecas.'],
  ['Varejo', 'TOTVS Home Center - Linha GEMCO', 'ERP para home center.', 'Lojas de material de construcao.', 'Controlar loja, estoque e venda.'],
  ['Varejo', 'TOTVS Lojas - Linha Protheus', 'ERP para lojas.', 'Redes varejistas.', 'Gerir vendas, estoque e fiscal.'],
  ['Varejo', 'TOTVS Postos de Combustiveis', 'Gestao de postos.', 'Postos e redes.', 'Controlar bombas, loja e financeiro.'],
  ['Varejo', 'VarejOnline by TOTVS', 'Gestao varejista em nuvem.', 'Lojas e redes varejistas.', 'Controlar operacao de loja.'],
  ['Varejo', 'TOTVS Linha Chef', 'Gestao food service.', 'Restaurantes e bares.', 'Controlar salao, cozinha e caixa.'],
  ['Varejo', 'TOTVS Food Service', 'Gestao para alimentacao.', 'Restaurantes, franquias e redes.', 'Integrar pedido, producao e pagamento.'],
  ['Varejo', 'Autopagamento by Gototem', 'Totem de autoatendimento.', 'Restaurantes e varejo.', 'Reduzir fila e agilizar venda.'],
  ['Varejo', 'TOTVS Linha Consinco', 'ERP para supermercados.', 'Supermercados e atacarejos.', 'Controlar compras, loja e estoque.'],
  ['Varejo', 'TOTVS Linha RMS', 'ERP para supermercados e varejo.', 'Supermercados e redes.', 'Controlar operacao varejista.'],
  ['Varejo', 'TOTVS PDV', 'Frente de caixa.', 'Lojas e supermercados.', 'Registrar vendas.'],
  ['Varejo', 'TOTVS PDV Omni', 'PDV omnichannel.', 'Varejo com canais integrados.', 'Unificar loja fisica e digital.'],
  ['Varejo', 'PDV Mobile by Easy Analytics', 'PDV no mobile.', 'Varejo.', 'Vender com mobilidade.'],
  ['Varejo', 'TOTVS WMS - Linha Protheus', 'Armazem Protheus.', 'Varejo e distribuicao.', 'Controlar estoque.'],
  ['Varejo', 'TOTVS WMS - Linha Datasul', 'Armazem Datasul.', 'Varejo e industria.', 'Controlar armazem.'],
  ['Varejo', 'Index', 'Produto de indice e gestao comercial.', 'Distribuicao e varejo.', 'Apoiar decisoes comerciais.'],
  ['Varejo', 'Conector Ifood', 'Integracao com iFood.', 'Supermercados e restaurantes.', 'Receber pedidos integrados.'],
  ['Varejo', 'Conciliacao Financeira by Boavista', 'Conciliacao financeira.', 'Financeiro e varejo.', 'Conferir recebimentos.'],
  ['Varejo', 'App Minha Gestao de Lojas', 'Gestao mobile de loja.', 'Gerentes.', 'Acompanhar operacao.'],
  ['Varejo', 'App Meu Fiscal de Caixa', 'Fiscal de caixa mobile.', 'Supermercados e varejo.', 'Apoiar fechamento e conferencia.'],
  ['Varejo', 'App Meu Papa Filas', 'Venda e fila mobile.', 'Varejo.', 'Reduzir filas.'],
  ['Varejo', 'App Minhas Compras', 'Compras mobile.', 'Compras e varejo.', 'Apoiar pedidos.'],
  ['Varejo', 'App Minha Comanda Restaurante', 'Comanda mobile.', 'Restaurantes.', 'Registrar pedidos.'],

  ['Servicos TOTVS', 'TOTVS Cloud', 'Hospedar sistemas em nuvem.', 'Empresas clientes TOTVS.', 'Reduzir infraestrutura local.'],
  ['Servicos TOTVS', 'TOTVS PaaS', 'Plataforma como servico.', 'TI e desenvolvimento.', 'Rodar aplicacoes com infraestrutura gerenciada.'],
  ['Servicos TOTVS', 'TOTVS IaaS', 'Infraestrutura como servico.', 'TI.', 'Ter servidores e infraestrutura em nuvem.'],
  ['Servicos TOTVS', 'Meu T-Cloud', 'Portal e gestao cloud.', 'Clientes TOTVS Cloud.', 'Gerenciar ambiente cloud.'],
  ['Servicos TOTVS', 'TOTVS Fabrica de Software', 'Desenvolvimento sob demanda.', 'Empresas que precisam customizar sistemas.', 'Criar e adaptar solucoes.'],
  ['Servicos TOTVS', 'TOTVS Suporte e Sustentacao', 'Suporte tecnico.', 'Clientes TOTVS.', 'Manter operacao funcionando.'],
  ['Servicos TOTVS', 'TOTVS BSO', 'Sustentacao e outsourcing de sistemas.', 'Empresas com sistemas criticos.', 'Ter apoio operacional continuo.'],
  ['Servicos TOTVS', 'TOTVS Legal Data', 'Servico ligado a dados legais e juridicos.', 'Juridico e compliance.', 'Apoiar gestao legal.'],
  ['Servicos TOTVS', 'TOTVS Prime Agil', 'Servico recorrente e consultivo.', 'Clientes TOTVS.', 'Evoluir o ambiente com agilidade.'],
  ['Servicos TOTVS', 'TOTVS Infraestrutura de Sistemas', 'Analise e sustentacao de infraestrutura.', 'TI.', 'Melhorar performance e estabilidade.'],
  ['Servicos TOTVS', 'TOTVS Upgrade de Releases', 'Atualizacao de versao.', 'Clientes com versoes antigas.', 'Manter sistema atualizado.'],
  ['Servicos TOTVS', 'TOTVS Treinamentos', 'Capacitacao.', 'Usuarios e times tecnicos.', 'Ensinar uso correto dos sistemas.'],
];

export const totvsProductsAndServicesCatalog: CompanyProductSettings[] = Array.from(
  new Map(
    catalog.map(([technology, name, about, targetAudience, solutionObjective]) => [
      name.toLocaleLowerCase(),
      {
        name,
        about,
        targetAudience,
        solutionObjective,
        technology,
        averagePrice: 'Sob consulta',
      },
    ]),
  ).values(),
);
